theme: jekyll-theme-minimal
show_downloads: [true]
google_analytics: [UA-104087733-5]
title: Catalysm CSGO config
description: Autoexec with scripts and binds for Counter Strike Global Offensive (CSGO).